
services:
    db:
      image: postgres:16-alpine
      container_name: estoque_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: estoque_user
        POSTGRES_PASSWORD: estoque_pass
        POSTGRES_DB: estoque_db
      ports:
        - "5432:5432"
      volumes:
        - estoque_db_data:/var/lib/postgresql/data

volumes:
  estoque_db_data:
